In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("employee_data.csv")

In [4]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [18]:
# df.columns
# df.head(3)
# df.tail(2)
# df.sample(3)

# df.info()

# df.describe()

df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [26]:
df = pd.read_csv("globalAirQuality.csv")

df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [69]:
df = pd.read_csv("raw_data.csv")
cleaned_data = df.copy()
cleaned_data

df.isna()

df.isna().sum()

df.dropna() #row
df.dropna(axis=1) #col

mean_avg = df["age"].mean()
cleaned_data = cleaned_data["age"].fillna(mean_avg)
cleaned_data

df.ffill()
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [76]:
df2 = df.copy()

df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 60000 else "10%" )

gender_mapping = {"Male" : "M", "Female" : "F", "Unknown" : "U"}

df2["gender"] = df2["gender"].map(gender_mapping)

df2 = df2.assign(new_income = df2["income"] * 1.1)

df2["country"] = df2["country"].replace("USA", "United States")

# df2[["name", "age", "country", "gender", "income", "tax", "new_income", "id"]]
(df2["id"], df2["income"]) = (df2["income"], df2["id"])

df2.rename(columns={"id":"income", "income": "id"}, inplace=True)
df2

     income          name   age        country gender  id  tax  new_income
0   55000.0      John Doe  29.0  United States      M   1  10%     60500.0
1   55000.0      John Doe  29.0  United States      M   1  10%     60500.0
2   62000.0    Jane Smith   NaN         Canada      F   2  20%     68200.0
3   47000.0          Alex   NaN  United States      U   3  10%     51700.0
4       NaN  Maria Garcia  34.0          Spain      F   4  10%         NaN
5   51000.0        Li Wei  27.0          China      M   5  10%     56100.0
6   73000.0           NaN  45.0          India      F   6  20%     80300.0
7   68000.0    Ahmed Khan  38.0            NaN      M   7  20%     74800.0
8   62000.0    Rachel Lee  29.0  United States      F   8  20%     68200.0
9   45000.0   Carlos Ruiz   NaN         Mexico      M   9  10%     49500.0
10  58000.0   Emily Davis  31.0  United States    NaN  10  10%     63800.0

In [85]:
df2 = df.copy()

df2 = df2.drop_duplicates()
df2= df2.fillna(0)

df2 = df2.sort_values("income")

df2 = df2.reset_index(drop=True)

df2.to_csv("sorted_data.csv")

In [87]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [130]:
idf = pd.read_csv("IRIS.csv")

idf2 = idf.copy()
# idf.describe()

idf2.head(10)
idf2.shape
idf2.dtypes


# idf2.loc[idf2["petal_lengt"] > 4.5]
# idf2.loc[idf2["species"] == "Iris-virginica"].count()

# idf2.groupby("species").agg(
#     avg_sepal_len=("sepal_length","mean"),
#     maximum_petal_width=("petal_width", "max"),
#     std_sepal_width=("sepal_width", "std")
# )
idf2
idf3 = idf2.assign(petal_ratio = idf2["petal_length"]/idf2["petal_width"])
idf3.groupby("species").agg(avg_petal_ratio=("petal_ratio", "mean"))

                 avg_petal_ratio
species
Iris-setosa             7.078000
Iris-versicolor         3.242837
Iris-virginica          2.780662

In [92]:
idf

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]